site_name: RailPhase
theme: readthedocs
docs_dir: 'Doc/'
pages:
- 'Documentation': 'index.md'
- 'Introduction': 'introduction.md'
- 'Templates': 'template_guide.md'
- 'Web server integration': 'server_integration.md'
- 'API Reference': 'api_reference.md'
